### ISSUE TITLE
Upstream to serde

### ISSUE THREAD

**Issue by figsoda** [dtolnay/path-to-error#17]
Is it possible for this to be upstreamed to serde perhaps as a feature?

**Comment by Dgame** [comment]
Any news on this? I would love to have that in serde built-in, maybe only for debug.

**Comment by dtolnay** [comment]
This is not something I am considering.

**Comment by Dgame** [comment]
> This is not something I am considering.

Alright. May I ask why? 🙂

**Comment by eopb** [comment]
I've created this crate for people who use `serde_json` and want `serde_path_to_error` to be the default.
https://crates.io/crates/serde_json_path_to_error
