### ISSUE TITLE
Expose serde_path_to_error::Error constructor

### ISSUE THREAD

**Issue by RReverser** [dtolnay/path-to-error#18]
Currently, when using the `serde_path_to_error::Deserializer` manually, it's not possible to wrap the resulting error + `track.path()` into a `serde_path_to_error::Error` from outside the crate since its fields are hidden.

Users can create their own wrappers, but it would be more convenient to either make the fields public or expose an `Error::new` constructor for downstream users.

**Comment by dtolnay** [comment]
Added `Error::new` in 0.1.10.

**Comment by RReverser** [comment]
Thanks!
