### ISSUE TITLE
Do not print path when there is nothing to print

### ISSUE THREAD

**Issue by mladedav** [dtolnay/path-to-error#19]
I realize this may be opinionated topic, but I want to at least propose this.

When the library is passed for example an invalid JSON such as `{invalid: json}` The error printed is
`?: key must be a string at line 1 column 2`. For example in axum which uses this for more inforamtion about a deserialization error this gets turned to `Failed to parse the request body as JSON: ?: key must be a string at line 1 column 2`.

The `?:` was a bit confusing for me and took me a while to figure out wher it came from. I would suggest to omit printing the path when it is exactly `?` as it provides no information. Alternatively translate that to something else more descriptive about where the origin is coming from (this would always be an unknown top level key right?).

If this is a change you would be willing to accept I would be glad to create a PR.

**Comment by dtolnay** [comment]
Fixed in 0.1.10.
