### ISSUE TITLE
Error doesn't implement `std::error::Error`

### ISSUE THREAD

**Issue by vorner** [dtolnay/path-to-error#2]
Hello

I'd like to ask if not implementing `std::error::Error` on the `Error` type is just an omission or if it is on purpose. If it's omission, I can submit a MR, but I'm not 100% sure what to use as the `Display` ‒ maybe `"{}: {}", self.path(), self.inner()`?

**Comment by dtolnay** [comment]
I would accept a fix for this. That message looks good to me.
